use crate::models::Benchmark;

pub fn fixed_benchmarks() -> Vec<Benchmark> {
    vec![
        Benchmark::fixed(
            "counter",
            "Counter",
            "benches/implementations/counter/solidity/Counter.sol",
            "benches/implementations/counter/vyper/Counter.vy",
        ),
        Benchmark::fixed(
            "erc20_minimal",
            "Erc20Minimal",
            "benches/implementations/erc20_minimal/solidity/Erc20Minimal.sol",
            "benches/implementations/erc20_minimal/vyper/Erc20Minimal.vy",
        ),
        Benchmark::fixed(
            "erc20_permit_hashing",
            "Erc20PermitHashing",
            "benches/implementations/erc20_permit_hashing/solidity/Erc20PermitHashing.sol",
            "benches/implementations/erc20_permit_hashing/vyper/Erc20PermitHashing.vy",
        ),
        Benchmark::fixed(
            "ownable_pausable",
            "OwnablePausable",
            "benches/implementations/ownable_pausable/solidity/OwnablePausable.sol",
            "benches/implementations/ownable_pausable/vyper/OwnablePausable.vy",
        ),
        Benchmark::fixed(
            "vault_deposit_withdraw",
            "VaultDepositWithdraw",
            "benches/implementations/vault_deposit_withdraw/solidity/VaultDepositWithdraw.sol",
            "benches/implementations/vault_deposit_withdraw/vyper/VaultDepositWithdraw.vy",
        ),
        Benchmark::fixed(
            "factory_create2",
            "FactoryCreate2",
            "benches/implementations/factory_create2/solidity/FactoryCreate2.sol",
            "benches/implementations/factory_create2/vyper/FactoryCreate2.vy",
        ),
        Benchmark::fixed(
            "minimal_proxy",
            "MinimalProxy",
            "benches/implementations/minimal_proxy/solidity/MinimalProxy.sol",
            "benches/implementations/minimal_proxy/vyper/MinimalProxy.vy",
        ),
        Benchmark::fixed(
            "merkle_verifier",
            "MerkleVerifier",
            "benches/implementations/merkle_verifier/solidity/MerkleVerifier.sol",
            "benches/implementations/merkle_verifier/vyper/MerkleVerifier.vy",
        ),
        Benchmark::fixed(
            "amm_pair_subset",
            "AmmPairSubset",
            "benches/implementations/amm_pair_subset/solidity/AmmPairSubset.sol",
            "benches/implementations/amm_pair_subset/vyper/AmmPairSubset.vy",
        ),
        Benchmark::fixed(
            "scaling_dispatch_N",
            "ScalingDispatchN",
            "benches/implementations/scaling_dispatch_N/solidity/ScalingDispatchN.sol",
            "benches/implementations/scaling_dispatch_N/vyper/ScalingDispatchN.vy",
        ),
    ]
}

pub fn all_benchmarks(generated: Vec<Benchmark>, only_benchmark: Option<&str>) -> Vec<Benchmark> {
    fixed_benchmarks()
        .into_iter()
        .chain(generated)
        .filter(|benchmark| only_benchmark.is_none_or(|id| id == benchmark.id))
        .collect()
}
